### ISSUE TITLE
Add Medal Ratings

### ISSUE THREAD

**Issue by Hubza** [osekai/osekai-medals-issues#10]
**Is your feature request related to a problem? Please describe.**
It's not obvious what medals are easy and what ones are hard. You could think this one looks easy, then 2 minutes later give up because it's too hard

**Describe the solution you'd like**
I think a star rating or something along the lines of that for difficulty would be nice, and then maybe some info, and the star rating shown on medal hover, or maybe just on the medal page itself.

**Comment by Hubza** [comment]
would like some other people's opinions on this

**Comment by mulraf** [comment]
yes something similar is planned

**Comment by Hubza** [comment]
alright, we can track the feature here then
