### ISSUE TITLE
medal links on medalRankings are broken

### ISSUE THREAD

**Issue by cl8n** [osekai/osekai-medals-issues#11]
https://osekai.net/medalRankings

links to each medal should go to /medals?medal=... , right now they 404

**Comment by Hubza** [comment]
for me they go to the correct url, is this still happening for you? if so what process are you using to open the link

**Comment by Hubza** [comment]
it 404s when opening in new tab, okay

**Comment by cl8n** [comment]
oh, yeah I guess it is only new tab. didn't think to check both sry

**Comment by Hubza** [comment]
just waiting for mulraf now

**Comment by mulraf** [comment]
fixed
