### ISSUE TITLE
You can add incorrect gamemode maps to gamemode specific medals.

### ISSUE THREAD

**Issue by Zozimoto** [osekai/osekai-medals-issues#8]
You can add maps which have a diffrent gamemode than the required one for the medal.

1. Go to the medals page
2. Click on a taiko only medal.
3. Press the add map button.
4. Insert catch map.

Expected behavior: The site doesn't allow you to add the map.

**Comment by Hubza** [comment]
@mulraf

**Comment by Hubza** [comment]
i'd assign him if he was in the organization

**Comment by mulraf** [comment]
fixed
